export const reactElement = Symbol('react.element')
export const reactText = Symbol('react.text')
export const classComponentFlag = Symbol('class.component')
export const reactForwardRef = Symbol('react.forward_ref')
export const reactFragment = Symbol('react.fragment')
export const elementInsert = Symbol('element.insert')
export const elementMove = Symbol('element.move')
